# Generated by Django 3.0.7 on 2021-02-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Automahnung',
            fields=[
                ('orderid', models.IntegerField(db_column='OrderID', primary_key=True, serialize=False)),
                ('mahnung1verschickt', models.DateTimeField(blank=True, db_column='Mahnung1verschickt', null=True)),
                ('mahnung2verschickt', models.DateTimeField(blank=True, db_column='Mahnung2verschickt', null=True)),
                ('mahnung3verschickt', models.DateTimeField(blank=True, db_column='Mahnung3verschickt', null=True)),
            ],
            options={
                'db_table': 'AutoMahnung',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companytype', models.CharField(db_column='CompanyType', max_length=50)),
            ],
            options={
                'db_table': 'Company Types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customerid', models.AutoField(db_column='CustomerID', primary_key=True, serialize=False)),
                ('employeeid', models.IntegerField(db_column='EmployeeID')),
                ('date', models.DateTimeField(db_column='Date')),
                ('companytypeid', models.IntegerField(db_column='CompanyTypeID')),
                ('companyname', models.CharField(db_column='CompanyName', max_length=50)),
                ('street', models.CharField(db_column='Street', max_length=50)),
                ('house', models.CharField(blank=True, db_column='House', max_length=50, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=50, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='PostalCode', max_length=20, null=True)),
                ('phonenumber', models.CharField(db_column='PhoneNumber', max_length=30, unique=True)),
                ('contact', models.CharField(blank=True, db_column='Contact', max_length=50, null=True)),
                ('deliverytimes', models.CharField(blank=True, db_column='DeliveryTimes', max_length=50, null=True)),
                ('closeddays', models.CharField(blank=True, db_column='ClosedDays', max_length=50, null=True)),
                ('callbackdate', models.DateTimeField(blank=True, db_column='CallBackDate', null=True)),
                ('protokoll', models.TextField(blank=True, db_column='Protokoll', null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('newtoggle', models.IntegerField(blank=True, db_column='NewToggle', null=True)),
                ('nichtmahnen', models.IntegerField(blank=True, db_column='NichtMahnen', null=True)),
            ],
            options={
                'db_table': 'Customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Editors',
            fields=[
                ('username', models.CharField(db_column='Username', max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Editors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employeeid', models.AutoField(db_column='EmployeeID', primary_key=True, serialize=False)),
                ('codename', models.CharField(db_column='Codename', max_length=50, unique=True)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=50, null=True)),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=50, null=True)),
                ('dateofbirth', models.DateTimeField(blank=True, db_column='DateOfBirth', null=True)),
                ('street', models.CharField(blank=True, db_column='Street', max_length=50, null=True)),
                ('house', models.CharField(blank=True, db_column='House', max_length=50, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=50, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='PostalCode', max_length=50, null=True)),
                ('phonenumber', models.CharField(blank=True, db_column='PhoneNumber', max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, db_column='Mobile', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyCompanyInformation',
            fields=[
                ('setupid', models.AutoField(db_column='SetupID', primary_key=True, serialize=False)),
                ('salestaxrate', models.FloatField(blank=True, db_column='SalesTaxRate', null=True)),
                ('companyname', models.CharField(db_column='CompanyName', max_length=50)),
                ('street', models.CharField(db_column='Street', max_length=50)),
                ('house', models.CharField(db_column='House', max_length=50)),
                ('city', models.CharField(db_column='City', max_length=50)),
                ('postalcode', models.CharField(db_column='PostalCode', max_length=20)),
                ('phonenumber', models.CharField(db_column='PhoneNumber', max_length=30)),
                ('faxnumber', models.CharField(blank=True, db_column='FaxNumber', max_length=30, null=True)),
                ('defaultpaymentterms', models.CharField(blank=True, db_column='DefaultPaymentTerms', max_length=255, null=True)),
                ('bankdetails', models.CharField(blank=True, db_column='BankDetails', max_length=255, null=True)),
            ],
            options={
                'db_table': 'My Company Information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oldinvoicelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField(db_column='OrderID')),
                ('nichtmahnen', models.IntegerField(blank=True, db_column='NichtMahnen', null=True)),
            ],
            options={
                'db_table': 'OldInvoiceList',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('orderdetailid', models.AutoField(db_column='OrderDetailID', primary_key=True, serialize=False)),
                ('orderid', models.IntegerField(db_column='OrderID')),
                ('productid', models.IntegerField(db_column='ProductID')),
                ('quantity', models.FloatField(db_column='Quantity')),
                ('units', models.IntegerField(db_column='Units')),
                ('unitprice', models.DecimalField(db_column='UnitPrice', decimal_places=4, max_digits=19)),
                ('commission', models.FloatField(db_column='Commission')),
                ('variable', models.IntegerField(db_column='Variable')),
            ],
            options={
                'db_table': 'Order Details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.AutoField(db_column='OrderID', primary_key=True, serialize=False)),
                ('customerid', models.IntegerField(db_column='CustomerID')),
                ('employeeid', models.IntegerField(db_column='EmployeeID')),
                ('orderdate', models.DateTimeField(blank=True, db_column='OrderDate', null=True)),
                ('invoicenumber', models.CharField(blank=True, db_column='InvoiceNumber', max_length=50, null=True)),
                ('shipname', models.CharField(blank=True, db_column='ShipName', max_length=50, null=True)),
                ('shipstreet', models.CharField(blank=True, db_column='ShipStreet', max_length=50, null=True)),
                ('shiphouse', models.CharField(blank=True, db_column='ShipHouse', max_length=50, null=True)),
                ('shipcity', models.CharField(blank=True, db_column='ShipCity', max_length=50, null=True)),
                ('shippostalcode', models.CharField(blank=True, db_column='ShipPostalCode', max_length=20, null=True)),
                ('shipphonenumber', models.CharField(blank=True, db_column='ShipPhoneNumber', max_length=30, null=True)),
                ('shipdate', models.DateTimeField(blank=True, db_column='ShipDate', null=True)),
                ('shippingmethodid', models.IntegerField(blank=True, db_column='ShippingMethodID', null=True)),
                ('freightcharge', models.DecimalField(blank=True, db_column='FreightCharge', decimal_places=4, max_digits=19, null=True)),
                ('salestaxrate', models.FloatField(db_column='SalesTaxRate')),
                ('deliverytimes', models.CharField(blank=True, db_column='DeliveryTimes', max_length=50, null=True)),
                ('closeddays', models.CharField(blank=True, db_column='ClosedDays', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('priceadjustment', models.DecimalField(blank=True, db_column='PriceAdjustment', decimal_places=4, max_digits=19, null=True)),
                ('newcustomer', models.IntegerField(db_column='NewCustomer')),
            ],
            options={
                'db_table': 'Orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('paymentmethodid', models.AutoField(db_column='PaymentMethodID', primary_key=True, serialize=False)),
                ('paymentmethod', models.CharField(db_column='PaymentMethod', max_length=50)),
            ],
            options={
                'db_table': 'Payment Methods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('paymentid', models.AutoField(db_column='PaymentID', primary_key=True, serialize=False)),
                ('orderid', models.IntegerField(db_column='OrderID')),
                ('paymentamount', models.DecimalField(blank=True, db_column='PaymentAmount', decimal_places=4, max_digits=19, null=True)),
                ('paymentdate', models.DateTimeField(blank=True, db_column='PaymentDate', null=True)),
                ('paymentmethodid', models.IntegerField(blank=True, db_column='PaymentMethodID', null=True)),
                ('accountname', models.CharField(blank=True, db_column='AccountName', max_length=50, null=True)),
                ('sortcode', models.CharField(blank=True, db_column='SortCode', max_length=50, null=True)),
                ('accountnumber', models.CharField(blank=True, db_column='AccountNumber', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productid', models.AutoField(db_column='ProductID', primary_key=True, serialize=False)),
                ('productname', models.CharField(db_column='ProductName', max_length=255)),
                ('units', models.CharField(blank=True, db_column='Units', max_length=50, null=True)),
                ('unitprice', models.DecimalField(db_column='UnitPrice', decimal_places=4, max_digits=19)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('commission', models.FloatField(blank=True, db_column='Commission', null=True)),
                ('variable', models.IntegerField(blank=True, db_column='Variable', null=True)),
                ('dpdtext', models.CharField(blank=True, db_column='DPDText', max_length=50, null=True)),
                ('show', models.IntegerField(blank=True, db_column='Show', null=True)),
            ],
            options={
                'db_table': 'Products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingMethods',
            fields=[
                ('shippingmethodid', models.AutoField(db_column='ShippingMethodID', primary_key=True, serialize=False)),
                ('shippingmethod', models.CharField(db_column='ShippingMethod', max_length=20)),
            ],
            options={
                'db_table': 'Shipping Methods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stockcontrol',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('itemname', models.CharField(blank=True, db_column='ItemName', max_length=50, null=True)),
                ('initialcount', models.IntegerField(blank=True, db_column='InitialCount', null=True)),
            ],
            options={
                'db_table': 'StockControl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stockcontrolsettings',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('countdate', models.DateTimeField(blank=True, db_column='CountDate', null=True)),
            ],
            options={
                'db_table': 'StockControlSettings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwitchboardItems',
            fields=[
                ('switchboardid', models.IntegerField(db_column='SwitchboardID', primary_key=True, serialize=False)),
                ('itemnumber', models.IntegerField(db_column='ItemNumber')),
                ('itemtext', models.CharField(blank=True, db_column='ItemText', max_length=255, null=True)),
                ('command', models.IntegerField(blank=True, db_column='Command', null=True)),
                ('argument', models.CharField(blank=True, db_column='Argument', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Switchboard Items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwitchboardItems1',
            fields=[
                ('switchboardid', models.IntegerField(db_column='SwitchboardID', primary_key=True, serialize=False)),
                ('itemnumber', models.IntegerField(db_column='ItemNumber')),
                ('itemtext', models.CharField(blank=True, db_column='ItemText', max_length=255, null=True)),
                ('command', models.IntegerField(blank=True, db_column='Command', null=True)),
                ('argument', models.CharField(blank=True, db_column='Argument', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Switchboard Items1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('useralias', models.CharField(blank=True, db_column='UserAlias', max_length=255, null=True)),
                ('useranrede', models.CharField(blank=True, db_column='UserAnrede', max_length=255, null=True)),
                ('uservorname', models.CharField(blank=True, db_column='UserVorname', max_length=255, null=True)),
                ('usernachname', models.CharField(blank=True, db_column='UserNachname', max_length=255, null=True)),
                ('userpasswort', models.CharField(blank=True, db_column='UserPasswort', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
