# Generated by Django 3.0.7 on 2021-02-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companytypes',
            options={'managed': True},
        ),
    ]
