# Generated by Django 3.0.7 on 2021-02-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210212_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companytypes',
            options={'managed': False},
        ),
    ]
